set -g default-terminal "screen-256color"


## Replace prefix
set -g prefix C-a # default cmd to general tmux activities
unbind C-b
bind-key C-a send-prefix


## Useful keybinds
bind-key b set-option status		# hide/show status bar
# bind o movew -r 			# reorder windows
bind R source-file ~/.tmux.conf 	# reload tmux config


## Rebind window size management
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
## Bind window swapping
bind -r H swap-window -t -1
bind -r L swap-window -t +1
bind -r o last-window 			# move to last window


# Set vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane


# Create/Kill session
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind X confirm kill-session


# IDK
set -g mouse on


## Plugins
set -g @plugin 'tmux-plugins/tpm' 		# tmux plugin manager
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-continuum'	# save session
set -g @continuum-restore 'on' 			# enables autosave and auto restore tmux sessions
set -g @continuum-save-interval '15'
set -g @plugin 'tmux-plugins/tmux-resurrect'	# restore session
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'


## Theme config
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'basic'


# Handles plugin manager installation and execution - must be at the end!
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
